version: 0.2

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/promotick-container
#      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG="latest"

  build:
    commands:
      - gradle build -x test
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile .

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files: Dockerrun.aws.json